#!/bin/sh

# On Linux: apt-get install autotools-dev autoconf libtool
#

_run() {
    echo "running $@ ..."
    eval "$@" >/dev/null 2>&1
}

die() {
    echo $*
    exit 1
}

do_init() {
    _run autoreconf --force
    if test $? -ne 0
    then
        if test -e .ac-aux/missing
        then
            die fix your errors
        fi
    fi
    _run aclocal
    _run autoheader
    _run autoreconf
    _run automake --add-missing
    _run libtoolize
    _run make distclean
    _run autoreconf
    ./configure --prefix=$HOME --enable-debug
}

if test "$1" = "init"
then
    export LDFLAGS="-L$HOME/lib -L/usr/local/lib"
    export CFLAGS="-I$HOME/include -I/usr/local/include"
    do_init

elif test "$1" = "dev"
then
    export LDFLAGS="-L$HOME/lib -L/usr/local/lib"
    export CFLAGS="-I$HOME/include -I/usr/local/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev-cmp-debug"
then
    export LDFLAGS="-L$HOME/lib -L/usr/local/lib"
    export CFLAGS="-I$HOME/include -I/usr/local/include -DYM_CMP_DEBUG"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev-ndebug"
then
    export LDFLAGS="-L$HOME/lib -L/usr/local/lib"
    export CFLAGS="-I$HOME/include -I/usr/local/include"
    autoreconf --force
    ./configure --prefix=$HOME

elif test "$1" = "dist"
then
    unset LDFLAGS
    unset CFLAGS
    autoreconf
    ./configure
    make dist

    if test -f port/distinfo
    then
        truncate -s0 port/distinfo
    fi
    for i in *.tar.gz
    do
        cp -v $i /data0/mkushnir/distfiles/
        if test -f port/distinfo
        then
            /sbin/sha256 $i >port/distinfo
            echo "SIZE ($i) = `stat -f%z $i`" >>port/distinfo
        fi
    done

elif test "$1" = "du"
then
    find . -type f -name '*.[ch]' -ls | awk '{print $7;}' | (n=0; while read a; do n=$((n + a)); done; echo $n)
else
    echo "`basename $0` {init|dev|dist|dev-ndebug|du}"
fi
